# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad3990390a39d8195b2f45031d6e63df4396b91cce9da8472b99d7d315d7e7cf7708a5d3a09b9f3ad55839004698933ee5b3011fe3c1de21c52e77b56b0a24ed

test:
  secret_key_base: 22d6fee759f24b5f142897234533d42e584d76482d1754d741c23ed61f76c48b97fce12b18a8625e9115849dfd52afa8e1a7e25a79461f68075afdec7ec4869f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
